version: '3'

vars:
  # builds a minimalized `wasip2-example` guest module by disabling panic formatting
  # requires the nightly rust toolchain
  MINIMAL_WASM: '{{ default .MINIMAL_WASM false }}'

includes:
  wasip2-example:
    taskfile: wasip2-example/Taskfile.yml
    dir: wasip2-example


tasks:
  build:
    desc: Build the rspective rust project
    vars:
      DIR: '{{ default .USER_WORKING_DIR .DIR }}'
    dir: '{{ .DIR }}'
    cmds:
      - cargo build --release --target wasm32-wasip2
  run:
    desc: Runs the `wasmtime-run` host runtime which embedds the `wasip2-example` guest
    deps:
      - task: wasip2-example:build
    dir: wasmtime-run
    cmds:
      - cargo run
  print-wit:
    desc: Prints the wit file embedded into the wasip2-example output wasm file
    deps:
      - task: wasip2-example:build
    dir: wasip2-example/target/wasm32-wasip2/release
    cmds:
      - wasm-tools component wit wasip2_example.wasm
  fmt-cargo:
    desc: Format a Cargo.toml
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - taplo format Cargo.toml
