version: '3'

tasks:
  build:
    desc: Build the respective rust project
    # minimal compilation options needed to not include a lot of unneeded wit imports, see https://github.com/rust-lang/rust/issues/133235 and https://github.com/johnthagen/min-sized-rust
    cmds:
      - 'cargo {{ if eq .MINIMAL_WASM "true" }}+nightly {{ end }}build {{ if eq .MINIMAL_WASM "true" }}-Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort {{ end }}--release --target wasm32-wasip2'
    env:
      RUSTFLAGS: '{{ if eq .MINIMAL_WASM "true" }}-Zlocation-detail=none -Zfmt-debug=none{{ end }}'
